//! Build script: generates Kani and Verus foundation proofs by composing
//! `kani_proof()` / `verus_proof()` token streams from `#[derive(Elicit)]` game types.
//!
//! # How Kani composition works
//!
//! `#[derive(Elicit)]` emits a `kani_proof()` method on every type, returning a
//! `proc_macro2::TokenStream` of `#[kani::proof]` harness functions.
//!
//! This build script:
//!
//! 1. Calls `kani_proof()` on all game types (Player, Position, Board, Move, …)
//! 2. Deduplicates by function name (composite types re-emit leaf proofs)
//! 3. Writes self-contained Kani files to `src/kani_proofs/generated/`
//!
//! The generated files form the foundation layer.  Hand-written harnesses in
//! `src/kani_proofs/*.rs` prove domain-specific properties on top of them.
//!
//! # How Verus composition works
//!
//! Same pattern for `verus_proof()` → `src/verus_proofs/generated/`.

use elicitation::{Elicitation, VerifiedStateMachine};
use strictly_blackjack::{BlackjackMachine, Outcome as BjOutcome};
use strictly_craps::CrapsMachine;
use strictly_tictactoe::{
    Board, GameFinished, GameInProgress, GameResult, GameSetup, Move, Outcome as TttOutcome,
    Player, Position, Square, TicTacToeMachine,
};

fn main() {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by Cargo");
    let base = std::path::Path::new(&manifest_dir);

    let kani_gen = base.join("src/kani_proofs/generated");
    let verus_gen = base.join("src/verus_proofs/generated");
    let creusot_gen = base.join("src/creusot_proofs/generated");
    std::fs::create_dir_all(&kani_gen).expect("create src/kani_proofs/generated/");
    std::fs::create_dir_all(&verus_gen).expect("create src/verus_proofs/generated/");
    std::fs::create_dir_all(&creusot_gen).expect("create src/creusot_proofs/generated/");

    generate_tictactoe_kani(&kani_gen);
    generate_blackjack_kani(&kani_gen);
    generate_blackjack_verus(&verus_gen);
    generate_vsm_kani(&kani_gen);
    generate_vsm_creusot(&creusot_gen);
    generate_vsm_verus(&verus_gen);

    println!("cargo:rerun-if-changed=../strictly_tictactoe/src/types.rs");
    println!("cargo:rerun-if-changed=../strictly_tictactoe/src/typestate.rs");
    println!("cargo:rerun-if-changed=../strictly_tictactoe/src/action.rs");
    println!("cargo:rerun-if-changed=../strictly_tictactoe/src/vsm.rs");
    println!("cargo:rerun-if-changed=../strictly_blackjack/src/types.rs");
    println!("cargo:rerun-if-changed=../strictly_blackjack/src/ledger.rs");
    println!("cargo:rerun-if-changed=../strictly_blackjack/src/vsm.rs");
    println!("cargo:rerun-if-changed=../strictly_craps/src/vsm.rs");
}

// ─────────────────────────────────────────────────────────────────────────────
//  Kani: TicTacToe foundation
// ─────────────────────────────────────────────────────────────────────────────

/// Generate `tictactoe_foundation.rs` from composed `kani_proof()` streams.
///
/// Calls `kani_proof()` on each TicTacToe type and deduplicates by function
/// name, since composite types re-emit their field types' proofs.
fn generate_tictactoe_kani(gen_dir: &std::path::Path) {
    // Collect in leaf-to-root order so leaf proofs appear first.
    let streams = [
        Player::kani_proof(),
        Position::kani_proof(),
        Square::kani_proof(),
        Board::kani_proof(),
        Move::kani_proof(),
        TttOutcome::kani_proof(),
        GameSetup::kani_proof(),
        GameInProgress::kani_proof(),
        GameFinished::kani_proof(),
        GameResult::kani_proof(),
    ];

    let body = dedup_kani_proofs(&streams);
    let imports = extract_used_types(&body);

    let formatted_body = format_generated(&body);
    let code = format!(
        "// AUTO-GENERATED by strictly_proofs/build.rs — DO NOT EDIT\n\
         // Regenerate: cargo build -p strictly_proofs\n\
         //\n\
         // Composition: Type::kani_proof() for all TicTacToe types (deduplicated).\n\
         // These foundation proofs underpin domain-specific harnesses in game_invariants.rs\n\
         // and tictactoe_contracts.rs.\n\
         use strictly_tictactoe::{{{imports}}};\n\n\
         {formatted_body}",
        imports = imports.join(", "),
    );

    let path = gen_dir.join("tictactoe_foundation.rs");
    std::fs::write(&path, code).expect("write tictactoe_foundation.rs");
    fmt_file(&path);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Kani: Blackjack foundation
// ─────────────────────────────────────────────────────────────────────────────

/// Generate `blackjack_foundation.rs` from composed `kani_proof()` streams.
fn generate_blackjack_kani(gen_dir: &std::path::Path) {
    use strictly_blackjack::{Card, Rank, Suit};

    let streams = [
        Rank::kani_proof(),
        Suit::kani_proof(),
        Card::kani_proof(),
        BjOutcome::kani_proof(),
    ];

    let body = dedup_kani_proofs(&streams);
    let imports = extract_used_types(&body);

    let formatted_body = format_generated(&body);
    let code = format!(
        "// AUTO-GENERATED by strictly_proofs/build.rs — DO NOT EDIT\n\
         // Regenerate: cargo build -p strictly_proofs\n\
         //\n\
         // Composition: Type::kani_proof() for all Blackjack types (deduplicated).\n\
         use strictly_blackjack::{{{imports}}};\n\n\
         {formatted_body}",
        imports = imports.join(", "),
    );

    let path = gen_dir.join("blackjack_foundation.rs");
    std::fs::write(&path, code).expect("write blackjack_foundation.rs");
    fmt_file(&path);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Verus: Blackjack foundation (unchanged)
// ─────────────────────────────────────────────────────────────────────────────

/// Generate `blackjack_foundation.rs` (Verus) by composing `verus_proof()` streams.
fn generate_blackjack_verus(gen_dir: &std::path::Path) {
    let u64_proof = <u64 as Elicitation>::verus_proof().to_string();
    let outcome_proof = BjOutcome::verus_proof().to_string();

    let stub = r"
pub struct U64Default { pub value: u64 }

impl U64Default {
    pub fn new(value: u64) -> (result: Self)
        ensures result.value == value,
    {
        U64Default { value }
    }

    pub fn into_inner(self) -> (result: u64)
        ensures result == self.value,
    {
        self.value
    }
}";

    let outcome_mirror = r"
#[derive(PartialEq, Eq)]
pub enum Outcome { Win, Blackjack, Push, Loss, Surrender }";

    let code = format!(
        r#"#![rustfmt::skip]
// AUTO-GENERATED by strictly_proofs/build.rs — DO NOT EDIT
// Regenerate: cargo build -p strictly_proofs
//
// Composition:
//   <u64 as Elicitation>::verus_proof()   BankrollLedger field types (deduped)
//   Outcome::verus_proof()                game enum identity roundtrip
//
// These foundation proofs underpin the business logic in bankroll_financial.rs.
use verus_builtin::*;
use verus_builtin_macros::*;
use vstd::prelude::*;

verus! {{

// ============================================================================
// ELICITATION WRAPPER STUB
// U64Default is elicitation's identity wrapper around u64.
// Required because u64::verus_proof() generates code that calls
// U64Default::new() / into_inner() to round-trip through the wrapper.
// ============================================================================
{stub}

// ============================================================================
// GAME TYPE MIRROR
// Source: strictly_blackjack::Outcome
// Must stay in sync when variants are added or removed.
// ============================================================================
{outcome_mirror}

// ============================================================================
// COMPOSED FOUNDATION PROOFS (generated by verus_proof() composition)
// ============================================================================

// From: <u64 as Elicitation>::verus_proof()
// Represents the deduplicated composition of BankrollLedger::verus_proof()
// (BankrollLedger has two u64 fields; we emit this proof once, not twice).
{u64_proof}

// From: Outcome::verus_proof()
// Proves that the Outcome enum identity function preserves its argument.
{outcome_proof}

}} // verus!
"#,
        stub = stub,
        outcome_mirror = outcome_mirror,
        u64_proof = u64_proof,
        outcome_proof = outcome_proof,
    );

    let path = gen_dir.join("blackjack_foundation.rs");
    std::fs::write(&path, code).expect("write verus blackjack_foundation.rs");
    fmt_file(&path);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Kani: VSM companions
// ─────────────────────────────────────────────────────────────────────────────

fn generate_vsm_kani(gen_dir: &std::path::Path) {
    let body = dedup_kani_proofs(&[TicTacToeMachine::vsm_kani_proof()]);
    write_vsm_kani_file(
        gen_dir,
        "tictactoe_vsm.rs",
        "TicTacToeMachine",
        "strictly_tictactoe",
        &body,
    );

    let body = dedup_kani_proofs(&[BlackjackMachine::vsm_kani_proof()]);
    write_vsm_kani_file(
        gen_dir,
        "blackjack_vsm.rs",
        "BlackjackMachine",
        "strictly_blackjack",
        &body,
    );

    let body = dedup_kani_proofs(&[CrapsMachine::vsm_kani_proof()]);
    write_vsm_kani_file(
        gen_dir,
        "craps_vsm.rs",
        "CrapsMachine",
        "strictly_craps",
        &body,
    );
}

fn write_vsm_kani_file(
    gen_dir: &std::path::Path,
    filename: &str,
    machine: &str,
    krate: &str,
    body: &str,
) {
    let raw = format!(
        "#[cfg(kani)] use elicitation::Established;\n\
         #[cfg(kani)] use {krate}::*;\n\
         {body}"
    );
    let formatted = syn::parse_file(&raw)
        .map(|f| prettyplease::unparse(&f))
        .unwrap_or(raw);
    let code = format!(
        "// AUTO-GENERATED by strictly_proofs/build.rs — DO NOT EDIT\n\
         // Regenerate: cargo build -p strictly_proofs\n\
         //\n\
         // Composed Kani VSM proof harnesses for {machine}.\n\n\
         {formatted}"
    );
    let path = gen_dir.join(filename);
    std::fs::write(&path, &code).unwrap_or_else(|e| panic!("write {filename}: {e}"));
    fmt_file(&path);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Creusot: VSM companions
// ─────────────────────────────────────────────────────────────────────────────

const INV_TTT_CREUSOT: &str = concat!(
    "#[cfg(creusot)] #[logic]",
    " pub fn tic_tac_toe_consistent(state: &TicTacToeState) -> bool {",
    " pearlite! { match state {",
    " TicTacToeState::Setup { .. } => true,",
    " TicTacToeState::InProgress { inner, .. } => inner.history@.len() <= 9,",
    " TicTacToeState::Finished { inner, .. } => inner.history@.len() >= 5,",
    " } } }",
);

const INV_BLACKJACK_CREUSOT: &str = concat!(
    "#[cfg(creusot)] #[logic]",
    " pub fn blackjack_consistent(state: &BlackjackState) -> bool {",
    " pearlite! { match state {",
    " BlackjackState::Setup { .. } => true,",
    " BlackjackState::Betting { inner, .. } => inner.bankroll@ > 0,",
    " BlackjackState::PlayerTurn { inner, .. } => inner.current_hand_index@ < inner.num_hands@,",
    " BlackjackState::DealerTurn { .. } => true,",
    " BlackjackState::Finished { inner, .. } => inner.num_hands@ <= MAX_PLAYER_HANDS@,",
    " } } }",
);

const INV_CRAPS_CREUSOT: &str = concat!(
    "#[cfg(creusot)] #[logic]",
    " pub fn craps_consistent(state: &CrapsState) -> bool {",
    " pearlite! { match state {",
    " CrapsState::Setup { inner, .. } => inner.num_seats@ > 0,",
    " CrapsState::Betting { inner, .. } => inner.shooter_idx@ < inner.bankrolls@.len(),",
    " CrapsState::ComeOut { inner, .. } => inner.shooter_idx@ < inner.bankrolls@.len(),",
    " CrapsState::PointPhase { inner, .. } => inner.shooter_idx@ < inner.bankrolls@.len(),",
    " CrapsState::Resolved { inner, .. } => inner.shooter_idx@ < inner.bankrolls@.len(),",
    " } } }",
);

fn generate_vsm_creusot(gen_dir: &std::path::Path) {
    write_vsm_creusot_file(
        gen_dir,
        "tictactoe_vsm.rs",
        "TicTacToeMachine",
        "strictly_tictactoe",
        INV_TTT_CREUSOT,
        &TicTacToeMachine::vsm_creusot_proof(),
    );
    write_vsm_creusot_file(
        gen_dir,
        "blackjack_vsm.rs",
        "BlackjackMachine",
        "strictly_blackjack",
        INV_BLACKJACK_CREUSOT,
        &BlackjackMachine::vsm_creusot_proof(),
    );
    write_vsm_creusot_file(
        gen_dir,
        "craps_vsm.rs",
        "CrapsMachine",
        "strictly_craps",
        INV_CRAPS_CREUSOT,
        &CrapsMachine::vsm_creusot_proof(),
    );
}

fn write_vsm_creusot_file(
    gen_dir: &std::path::Path,
    filename: &str,
    machine: &str,
    krate: &str,
    inv_logic: &str,
    body: &proc_macro2::TokenStream,
) {
    let body_str = body.to_string();
    let raw = format!(
        "#[cfg(creusot)] use ::creusot_std::prelude::*;\n\
         #[cfg(creusot)] use elicitation::Established;\n\
         #[cfg(creusot)] use elicitation::kani_label;\n\
         #[cfg(creusot)] use {krate}::vsm::*;\n\
         #[cfg(creusot)] use {krate}::*;\n\
         {inv_logic}\n\
         {body_str}"
    );
    let formatted = syn::parse_file(&raw)
        .map(|f| prettyplease::unparse(&f))
        .unwrap_or(raw);
    let code = format!(
        "// AUTO-GENERATED by strictly_proofs/build.rs — DO NOT EDIT\n\
         // Regenerate: cargo build -p strictly_proofs\n\
         //\n\
         // Creusot companion contracts for {machine}.\n\n\
         {formatted}"
    );
    let path = gen_dir.join(filename);
    std::fs::write(&path, &code).unwrap_or_else(|e| panic!("write {filename}: {e}"));
    fmt_file(&path);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Verus: VSM companions
// ─────────────────────────────────────────────────────────────────────────────

const INV_TTT_VERUS: &str = concat!(
    "verus! {",
    " pub open spec fn tic_tac_toe_consistent(state: &TicTacToeState) -> bool {",
    " match *state {",
    " TicTacToeState::Setup { .. } => true,",
    " TicTacToeState::InProgress { inner, .. } => inner.history@.len() <= 9,",
    " TicTacToeState::Finished { inner, .. } => inner.history@.len() >= 5,",
    " } } }",
);

const INV_BLACKJACK_VERUS: &str = concat!(
    "verus! {",
    " pub open spec fn blackjack_consistent(state: &BlackjackState) -> bool {",
    " match *state {",
    " BlackjackState::Setup { .. } => true,",
    " BlackjackState::Betting { inner, .. } => inner.bankroll@ > 0,",
    " BlackjackState::PlayerTurn { inner, .. } => inner.current_hand_index@ < inner.num_hands@,",
    " BlackjackState::DealerTurn { .. } => true,",
    " BlackjackState::Finished { inner, .. } => inner.num_hands@ <= MAX_PLAYER_HANDS@,",
    " } } }",
);

const INV_CRAPS_VERUS: &str = concat!(
    "verus! {",
    " pub open spec fn craps_consistent(state: &CrapsState) -> bool {",
    " match *state {",
    " CrapsState::Setup { inner, .. } => inner.num_seats@ > 0,",
    " CrapsState::Betting { inner, .. } => inner.shooter_idx@ < inner.bankrolls@.len(),",
    " CrapsState::ComeOut { inner, .. } => inner.shooter_idx@ < inner.bankrolls@.len(),",
    " CrapsState::PointPhase { inner, .. } => inner.shooter_idx@ < inner.bankrolls@.len(),",
    " CrapsState::Resolved { inner, .. } => inner.shooter_idx@ < inner.bankrolls@.len(),",
    " } } }",
);

fn generate_vsm_verus(gen_dir: &std::path::Path) {
    write_vsm_verus_file(
        gen_dir,
        "tictactoe_vsm.rs",
        "TicTacToeMachine",
        "strictly_tictactoe",
        INV_TTT_VERUS,
        &TicTacToeMachine::vsm_verus_proof(),
    );
    write_vsm_verus_file(
        gen_dir,
        "blackjack_vsm.rs",
        "BlackjackMachine",
        "strictly_blackjack",
        INV_BLACKJACK_VERUS,
        &BlackjackMachine::vsm_verus_proof(),
    );
    write_vsm_verus_file(
        gen_dir,
        "craps_vsm.rs",
        "CrapsMachine",
        "strictly_craps",
        INV_CRAPS_VERUS,
        &CrapsMachine::vsm_verus_proof(),
    );
}

fn write_vsm_verus_file(
    gen_dir: &std::path::Path,
    filename: &str,
    machine: &str,
    krate: &str,
    inv_spec: &str,
    body: &proc_macro2::TokenStream,
) {
    let body_str = body.to_string();
    // These files are standalone Verus analysis targets — they are run directly
    // through the Verus binary, never included in normal Rust compilation via mod.rs.
    // Do NOT add #[cfg(verus)] gates: Verus panics on them (erase.rs:237).
    // #![rustfmt::skip] prevents cargo fmt from mangling the Verus verus!{} syntax.
    let code = format!(
        "#![rustfmt::skip]\n\
         // AUTO-GENERATED by strictly_proofs/build.rs — DO NOT EDIT\n\
         // Regenerate: cargo build -p strictly_proofs\n\
         //\n\
         // Verus companion contracts for {machine}.\n\
         // Run via: just verify-verus-tracked\n\n\
         use ::vstd::prelude::*;\n\
         use ::verus_builtin_macros::verus;\n\
         use elicitation::Established;\n\
         use {krate}::*;\n\
         {inv_spec}\n\
         {body_str}\n"
    );
    let path = gen_dir.join(filename);
    std::fs::write(&path, &code).unwrap_or_else(|e| panic!("write {filename}: {e}"));
    fmt_file(&path);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Deduplication helpers
// ─────────────────────────────────────────────────────────────────────────────

fn fmt_file(path: &std::path::Path) {
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_string());
    // Use `cargo fmt` (not bare `rustfmt`) so it reads the correct edition and
    // workspace rustfmt.toml.  We pass the absolute file path after `--` so
    // rustfmt formats only this file instead of the whole crate.
    let manifest =
        std::path::Path::new(&std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"))
            .join("Cargo.toml");
    let status = std::process::Command::new(&cargo)
        .arg("fmt")
        .arg("--manifest-path")
        .arg(&manifest)
        .arg("--")
        .arg(path.canonicalize().unwrap_or_else(|_| path.to_path_buf()))
        .status()
        .unwrap_or_else(|e| panic!("failed to spawn cargo fmt on {}: {e}", path.display()));
    assert!(
        status.success(),
        "cargo fmt failed on {} — fix the generated code template in build.rs",
        path.display()
    );
}

/// Format a generated Rust code string with `prettyplease`.
///
/// Falls back to the raw string if parsing fails (e.g. when the token stream
/// contains syntax that `syn` cannot round-trip, such as Verus extensions).
fn format_generated(raw: &str) -> String {
    syn::parse_file(raw)
        .map(|f| prettyplease::unparse(&f))
        .unwrap_or_else(|_| raw.to_string())
}

/// Compose multiple `kani_proof()` token streams, deduplicating by function name.
///
/// `#[derive(Elicit)]` on composite types recursively includes field-type proofs.
/// Without deduplication, `verify_player_constructible` would appear once per
/// type that contains a `Player` field — causing duplicate symbol errors.
fn dedup_kani_proofs(streams: &[proc_macro2::TokenStream]) -> String {
    let mut seen = std::collections::HashSet::new();
    let mut result = String::new();

    for ts in streams {
        let s = ts.to_string();
        for chunk in extract_proof_chunks(&s) {
            if let Some(name) = extract_fn_name(&chunk)
                && seen.insert(name)
            {
                result.push_str(&chunk);
                result.push('\n');
            }
        }
    }

    result
}

/// Split a serialised token stream into individual proof-function strings.
///
/// Each proof chunk starts with `# [` (a `#[...]` attribute) and ends at the
/// closing `}` of the function body.  Brace depth tracks nesting.
fn extract_proof_chunks(s: &str) -> Vec<String> {
    let mut chunks = Vec::new();
    let bytes = s.as_bytes();
    let len = bytes.len();
    let mut i = 0;

    while i < len {
        // Find start of a `# [` attribute sequence.
        if i + 3 <= len && &s[i..i + 3] == "# [" {
            let start = i;
            let mut depth: i32 = 0;
            let mut found_brace = false;
            let mut j = i;

            while j < len {
                match bytes[j] {
                    b'{' => {
                        depth += 1;
                        found_brace = true;
                    }
                    b'}' => {
                        depth -= 1;
                        if found_brace && depth == 0 {
                            chunks.push(s[start..=j].to_string());
                            i = j + 1;
                            break;
                        }
                    }
                    _ => {}
                }
                j += 1;
            }
            if j >= len {
                break;
            }
        } else {
            i += 1;
        }
    }

    chunks
}

/// Extract the function name from a proof chunk string (the word after `fn `).
fn extract_fn_name(chunk: &str) -> Option<String> {
    let fn_pos = chunk.find("fn ")?;
    let after_fn = &chunk[fn_pos + 3..];
    let name_end = after_fn
        .find(|c: char| !c.is_alphanumeric() && c != '_')
        .unwrap_or(after_fn.len());
    Some(after_fn[..name_end].to_string())
}

/// Scan the generated body and return a sorted list of type names that are
/// actually referenced.
///
/// Two patterns are detected:
/// - `TYPE ::` — enum variant / associated item (`Player :: X`)
/// - `: TYPE` — type annotation (`let _ : Board = kani :: any ()`)
///
/// Only capitalised identifiers are collected; built-ins like `bool` are ignored.
fn extract_used_types(body: &str) -> Vec<String> {
    let tokens: Vec<&str> = body.split_whitespace().collect();
    let mut types = std::collections::BTreeSet::new();
    for window in tokens.windows(2) {
        let is_upper = |s: &str| s.chars().next().is_some_and(|c| c.is_uppercase());
        // Pattern: TYPE :: (enum variant / associated item)
        if window[1] == "::" && is_upper(window[0]) {
            types.insert(window[0].to_string());
        }
        // Pattern: : TYPE (type annotation) — token before is ":" or ">"
        if window[0] == ":" && is_upper(window[1]) {
            types.insert(window[1].to_string());
        }
    }
    types.into_iter().collect()
}
