//! Build script: generates Verus foundation proofs by composing `verus_proof()`
//! token streams from `#[derive(Elicit)]` game types.
//!
//! # How composition works
//!
//! Every type that `#[derive(Elicit)]` emits a `verus_proof()` associated
//! function returning a `proc_macro2::TokenStream` of Verus proof code.
//! This build script:
//!
//! 1. Calls `verus_proof()` on the game types (Outcome, u64 field foundation)
//! 2. Converts the token streams to strings
//! 3. Writes self-contained Verus files to `src/verus_proofs/generated/`
//!
//! The generated files serve as the foundation layer for the hand-written
//! business logic proofs in `src/verus_proofs/*.rs`.
//!
//! # Why not call `BankrollLedger::verus_proof()` directly?
//!
//! `BankrollLedger` has two `u64` fields (`post_bet_balance`, `bet`).  The
//! derive-generated `verus_proof()` calls `<u64 as Elicitation>::verus_proof()`
//! **twice** — once per field — which would emit duplicate function definitions.
//! We therefore call each unique field type's `verus_proof()` exactly once,
//! which is semantically equivalent to the deduplicated composition of
//! `BankrollLedger::verus_proof()`.

use elicitation::Elicitation;
use strictly_blackjack::Outcome;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by Cargo");
    let gen_dir = std::path::Path::new(&manifest_dir).join("src/verus_proofs/generated");
    std::fs::create_dir_all(&gen_dir).expect("create src/verus_proofs/generated/");

    generate_blackjack_foundation(&gen_dir);

    // Regenerate when source types change.
    println!("cargo:rerun-if-changed=../strictly_blackjack/src/types.rs");
    println!("cargo:rerun-if-changed=../strictly_blackjack/src/ledger.rs");
}

/// Generate `blackjack_foundation.rs` by composing `verus_proof()` token
/// streams from the blackjack game types.
fn generate_blackjack_foundation(gen_dir: &std::path::Path) {
    // ── Compose from verus_proof() ───────────────────────────────────────────
    //
    // BankrollLedger::verus_proof() composes its field types' proofs.
    // Fields: post_bet_balance: u64, bet: u64  →  u64::verus_proof() × 2
    // We call it once (deduped) to avoid duplicate function definitions.
    let u64_proof = <u64 as Elicitation>::verus_proof().to_string();

    // Outcome::verus_proof() emits verify_outcome_roundtrip (identity proof).
    let outcome_proof = Outcome::verus_proof().to_string();

    // ── Wrapper stub ─────────────────────────────────────────────────────────
    //
    // u64::verus_proof() generates code referencing U64Default (elicitation's
    // identity wrapper around u64).  We provide a minimal Verus-compatible stub
    // so the generated proof can be verified standalone.
    let stub = r"
pub struct U64Default { pub value: u64 }

impl U64Default {
    pub fn new(value: u64) -> (result: Self)
        ensures result.value == value,
    {
        U64Default { value }
    }

    pub fn into_inner(self) -> (result: u64)
        ensures result == self.value,
    {
        self.value
    }
}";

    // ── Outcome mirror ───────────────────────────────────────────────────────
    //
    // Outcome::verus_proof() references the `Outcome` type by name.  Verus
    // cannot resolve workspace deps so we define a local mirror here.
    // Maintenance: keep in sync with strictly_blackjack::Outcome.
    let outcome_mirror = r"
#[derive(PartialEq, Eq)]
pub enum Outcome { Win, Blackjack, Push, Loss, Surrender }";

    // ── Assemble the file ────────────────────────────────────────────────────
    let code = format!(
        r#"// AUTO-GENERATED by strictly_proofs/build.rs — DO NOT EDIT
// Regenerate: cargo build -p strictly_proofs
//
// Composition:
//   <u64 as Elicitation>::verus_proof()   BankrollLedger field types (deduped)
//   Outcome::verus_proof()                game enum identity roundtrip
//
// These foundation proofs underpin the business logic in bankroll_financial.rs.
use verus_builtin::*;
use verus_builtin_macros::*;
use vstd::prelude::*;

verus! {{

// ============================================================================
// ELICITATION WRAPPER STUB
// U64Default is elicitation's identity wrapper around u64.
// Required because u64::verus_proof() generates code that calls
// U64Default::new() / into_inner() to round-trip through the wrapper.
// ============================================================================
{stub}

// ============================================================================
// GAME TYPE MIRROR
// Source: strictly_blackjack::Outcome
// Must stay in sync when variants are added or removed.
// ============================================================================
{outcome_mirror}

// ============================================================================
// COMPOSED FOUNDATION PROOFS (generated by verus_proof() composition)
// ============================================================================

// From: <u64 as Elicitation>::verus_proof()
// Represents the deduplicated composition of BankrollLedger::verus_proof()
// (BankrollLedger has two u64 fields; we emit this proof once, not twice).
{u64_proof}

// From: Outcome::verus_proof()
// Proves that the Outcome enum identity function preserves its argument.
{outcome_proof}

}} // verus!
"#,
        stub = stub,
        outcome_mirror = outcome_mirror,
        u64_proof = u64_proof,
        outcome_proof = outcome_proof,
    );

    std::fs::write(gen_dir.join("blackjack_foundation.rs"), code)
        .expect("write blackjack_foundation.rs");
}
