//! Build script for `strictly_verus`.
//!
//! Generates self-contained Verus source files in `src/generated/` — one per game
//! VSM.  Unlike the files in `strictly_proofs/src/verus_proofs/generated/`, these
//! files do **not** import external crate rlibs.  Instead they define all required
//! types inline as stubs, allowing the Verus binary to verify them directly.
//!
//! # Architecture
//!
//! Each generated file contains:
//!
//! 1. **Inline stub types** (`STUBS_*_VERUS`) — state enums and proof marker types
//!    defined with only the fields that the invariant spec fn references.
//! 2. **Invariant spec fn** (`INV_*_VERUS`) — `pub open spec fn` that encodes the
//!    VSM invariant over the stub state type.
//! 3. **`#[verifier::external]` stubs** — one per transition, generated by
//!    `VerifiedStateMachine::vsm_verus_transitions()`.  Provides a symbol for
//!    `assume_specification` to target.
//! 4. **`assume_specification` contracts** — one per transition, also from
//!    `vsm_verus_transitions()`.  Axiomatises the invariant pre/postcondition.
//!
//! # Regenerating
//!
//! ```bash
//! cargo build -p strictly_verus
//! ```

use elicitation::contracts::VerifiedStateMachine;
use strictly_blackjack::vsm::BlackjackMachine;
use strictly_craps::vsm::CrapsMachine;
use strictly_tictactoe::vsm::TicTacToeMachine;

// ── Inline stub types ─────────────────────────────────────────────────────────
//
// These define only the fields referenced by the invariant spec fn.
// All state variants use struct form (`{ inner: T }`) so that match patterns
// with `{ .. }` (as used in the invariant bodies) compile correctly.

const STUBS_BLACKJACK_VERUS: &str = concat!(
    "verus! {\n",
    "    use vstd::prelude::*;\n",
    "\n",
    "    /// Opaque proof-token type — body not verified by Verus.\n",
    "    #[verifier::external_body]\n",
    "    pub struct Established<#[verifier::reject_recursive_types] T> { _marker: std::marker::PhantomData<T> }\n",
    "\n",
    "    /// Proof marker: state satisfies the blackjack invariant.\n",
    "    #[derive(Clone)] pub struct BlackjackConsistent;\n",
    "    /// Proof marker: bankroll is positive.\n",
    "    #[derive(Clone)] pub struct BankrollPositive;\n",
    "    /// Proof marker: player action is valid.\n",
    "    #[derive(Clone)] pub struct ValidAction;\n",
    "    /// Proof marker: player hand is not bust.\n",
    "    #[derive(Clone)] pub struct NotBust;\n",
    "    /// A basic player action (stub — fields not needed for invariant).\n",
    "    #[derive(Clone)] pub struct BasicAction;\n",
    "\n",
    "    /// Stub inner type for variants with no invariant-relevant fields.\n",
    "    #[derive(Clone)] pub struct UnitInner;\n",
    "\n",
    "    /// Stub inner type for the Betting variant.\n",
    "    #[derive(Clone)] pub struct BjBettingInner { pub bankroll: u64 }\n",
    "\n",
    "    /// Stub inner type for the PlayerTurn variant.\n",
    "    #[derive(Clone)]\n",
    "    pub struct BjPlayerTurnInner {\n",
    "        pub current_hand_index: usize,\n",
    "        pub num_hands: usize,\n",
    "    }\n",
    "\n",
    "    /// Stub inner type for the Finished variant.\n",
    "    #[derive(Clone)] pub struct BjFinishedInner { pub num_hands: usize }\n",
    "\n",
    "    /// Maximum number of simultaneous player hands (mirrors hand.rs).\n",
    "    pub const MAX_PLAYER_HANDS: usize = 4usize;\n",
    "\n",
    "    /// Stub state enum — only invariant-relevant fields are present.\n",
    "    #[derive(Clone)]\n",
    "    pub enum BlackjackState {\n",
    "        /// Awaiting first player — no game data yet.\n",
    "        Setup { inner: UnitInner },\n",
    "        /// Player places initial wager.\n",
    "        Betting { inner: BjBettingInner },\n",
    "        /// Player draws / stands / splits.\n",
    "        PlayerTurn { inner: BjPlayerTurnInner },\n",
    "        /// Dealer plays by fixed rules.\n",
    "        DealerTurn { inner: UnitInner },\n",
    "        /// Round finished; outcomes determined.\n",
    "        Finished { inner: BjFinishedInner },\n",
    "    }\n",
    "}\n",
);

const STUBS_CRAPS_VERUS: &str = concat!(
    "verus! {\n",
    "    use vstd::prelude::*;\n",
    "\n",
    "    /// Opaque proof-token type — body not verified by Verus.\n",
    "    #[verifier::external_body]\n",
    "    pub struct Established<#[verifier::reject_recursive_types] T> { _marker: std::marker::PhantomData<T> }\n",
    "\n",
    "    /// Proof marker: state satisfies the craps invariant.\n",
    "    #[derive(Clone)] pub struct CrapsConsistent;\n",
    "    /// Proof marker: bankroll slice is non-empty.\n",
    "    #[derive(Clone)] pub struct NonEmptyBankrolls;\n",
    "    /// Proof marker: all seat bets are valid and funded.\n",
    "    #[derive(Clone)] pub struct BetsPlaced;\n",
    "    /// An individual active bet (stub — fields not needed for invariant).\n",
    "    #[derive(Clone)] pub struct ActiveBet;\n",
    "    /// A dice roll result (stub — value not needed for invariant).\n",
    "    #[derive(Clone)] pub struct DiceRoll;\n",
    "\n",
    "    /// Stub inner type for the Setup variant.\n",
    "    #[derive(Clone)] pub struct CrapsSetupInner { pub num_seats: usize }\n",
    "\n",
    "    /// Stub inner type for active-game variants (Betting / ComeOut / PointPhase / Resolved).\n",
    "    #[derive(Clone)]\n",
    "    pub struct CrapsActiveInner {\n",
    "        pub shooter_idx: usize,\n",
    "        pub bankrolls: Vec<u64>,\n",
    "    }\n",
    "\n",
    "    /// Stub state enum — only invariant-relevant fields are present.\n",
    "    #[derive(Clone)]\n",
    "    pub enum CrapsState {\n",
    "        /// Table configured, awaiting players.\n",
    "        Setup { inner: CrapsSetupInner },\n",
    "        /// Players place bets.\n",
    "        Betting { inner: CrapsActiveInner },\n",
    "        /// Come-out roll phase.\n",
    "        ComeOut { inner: CrapsActiveInner },\n",
    "        /// Point established; shooter rolls until point or seven.\n",
    "        PointPhase { inner: CrapsActiveInner },\n",
    "        /// Round resolved; bankrolls settled.\n",
    "        Resolved { inner: CrapsActiveInner },\n",
    "    }\n",
    "}\n",
);

const STUBS_TTT_VERUS: &str = concat!(
    "verus! {\n",
    "    use vstd::prelude::*;\n",
    "\n",
    "    /// Opaque proof-token type — body not verified by Verus.\n",
    "    #[verifier::external_body]\n",
    "    pub struct Established<#[verifier::reject_recursive_types] T> { _marker: std::marker::PhantomData<T> }\n",
    "\n",
    "    /// Proof marker: state satisfies the tic-tac-toe invariant.\n",
    "    #[derive(Clone)] pub struct TicTacToeConsistent;\n",
    "    /// A player token (X or O) — stub, value not needed for invariant.\n",
    "    #[derive(Clone)] pub struct Player;\n",
    "    /// A board move — stub, value not needed for invariant.\n",
    "    #[derive(Clone)] pub struct Move;\n",
    "    /// Proof marker: target square is empty.\n",
    "    #[derive(Clone)] pub struct SquareEmpty;\n",
    "    /// Proof marker: it is this player's turn.\n",
    "    #[derive(Clone)] pub struct PlayerTurn;\n",
    "\n",
    "    /// Stub inner type for the InProgress variant.\n",
    "    #[derive(Clone)] pub struct TttInProgressInner { pub history: Vec<u8> }\n",
    "\n",
    "    /// Stub inner type for the Finished variant.\n",
    "    #[derive(Clone)] pub struct TttFinishedInner { pub history: Vec<u8> }\n",
    "\n",
    "    /// Stub inner type for variants with no invariant-relevant fields.\n",
    "    #[derive(Clone)] pub struct UnitInner;\n",
    "\n",
    "    /// Stub state enum — only invariant-relevant fields are present.\n",
    "    #[derive(Clone)]\n",
    "    pub enum TicTacToeState {\n",
    "        /// Board not yet started.\n",
    "        Setup { inner: UnitInner },\n",
    "        /// Game in progress — history records moves made.\n",
    "        InProgress { inner: TttInProgressInner },\n",
    "        /// Game finished — at least 5 moves were played.\n",
    "        Finished { inner: TttFinishedInner },\n",
    "    }\n",
    "}\n",
);

// ── Invariant spec functions ──────────────────────────────────────────────────
//
// These match exactly the INV_*_VERUS constants in strictly_proofs/build.rs.
// Field names and types must align with the stub inner structs above.

const INV_BLACKJACK_VERUS: &str = concat!(
    "verus! {",
    " pub open spec fn blackjack_consistent(state: &BlackjackState) -> bool {",
    " match *state {",
    " BlackjackState::Setup { .. } => true,",
    " BlackjackState::Betting { inner, .. } => inner.bankroll@ > 0,",
    " BlackjackState::PlayerTurn { inner, .. } => inner.current_hand_index@ < inner.num_hands@,",
    " BlackjackState::DealerTurn { .. } => true,",
    " BlackjackState::Finished { inner, .. } => inner.num_hands@ <= MAX_PLAYER_HANDS@,",
    " } } }",
);

const INV_CRAPS_VERUS: &str = concat!(
    "verus! {",
    " pub open spec fn craps_consistent(state: &CrapsState) -> bool {",
    " match *state {",
    " CrapsState::Setup { inner, .. } => inner.num_seats@ > 0,",
    " CrapsState::Betting { inner, .. } => inner.shooter_idx@ < inner.bankrolls@.len(),",
    " CrapsState::ComeOut { inner, .. } => inner.shooter_idx@ < inner.bankrolls@.len(),",
    " CrapsState::PointPhase { inner, .. } => inner.shooter_idx@ < inner.bankrolls@.len(),",
    " CrapsState::Resolved { inner, .. } => inner.shooter_idx@ < inner.bankrolls@.len(),",
    " } } }",
);

const INV_TTT_VERUS: &str = concat!(
    "verus! {",
    " pub open spec fn tic_tac_toe_consistent(state: &TicTacToeState) -> bool {",
    " match *state {",
    " TicTacToeState::Setup { .. } => true,",
    " TicTacToeState::InProgress { inner, .. } => inner.history@.len() <= 9,",
    " TicTacToeState::Finished { inner, .. } => inner.history@.len() >= 5,",
    " } } }",
);

// ── Generation ────────────────────────────────────────────────────────────────

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let gen_dir = std::path::Path::new(&manifest).join("src/generated");
    std::fs::create_dir_all(&gen_dir).expect("create src/generated");

    write_standalone_verus_file(
        &gen_dir,
        "blackjack.rs",
        "BlackjackMachine",
        STUBS_BLACKJACK_VERUS,
        INV_BLACKJACK_VERUS,
        &BlackjackMachine::vsm_verus_transitions(),
    );
    write_standalone_verus_file(
        &gen_dir,
        "craps.rs",
        "CrapsMachine",
        STUBS_CRAPS_VERUS,
        INV_CRAPS_VERUS,
        &CrapsMachine::vsm_verus_transitions(),
    );
    write_standalone_verus_file(
        &gen_dir,
        "tictactoe.rs",
        "TicTacToeMachine",
        STUBS_TTT_VERUS,
        INV_TTT_VERUS,
        &TicTacToeMachine::vsm_verus_transitions(),
    );
}

fn write_standalone_verus_file(
    gen_dir: &std::path::Path,
    filename: &str,
    machine: &str,
    stub_types: &str,
    inv_spec: &str,
    transitions: &proc_macro2::TokenStream,
) {
    let transitions_str = transitions.to_string();
    // #![rustfmt::skip] prevents cargo fmt from trying to reformat Verus syntax.
    // These files are standalone Verus analysis targets — run via `just verify-verus-vsm`.
    // They are never included in normal Rust compilation.
    let code = format!(
        "#![rustfmt::skip]\n\
         // AUTO-GENERATED by strictly_verus/build.rs — DO NOT EDIT\n\
         // Regenerate: cargo build -p strictly_verus\n\
         //\n\
         // Self-contained Verus proof for {machine}.\n\
         // All types are defined inline — no external crate rlibs required.\n\
         // Run via: just verify-verus-vsm\n\n\
         use ::verus_builtin_macros::verus;\n\n\
         {stub_types}\n\
         {inv_spec}\n\
         {transitions_str}\n"
    );
    let path = gen_dir.join(filename);
    std::fs::write(&path, &code).unwrap_or_else(|e| panic!("write {filename}: {e}"));
    println!("cargo:rerun-if-changed=build.rs");
}
