//! Kani proofs for BankrollLedger financial typestate.
//!
//! Demonstrates how the elicitation framework's proof-carrying typestate
//! applies to high-assurance finance: the `Established<BetDeducted>` token
//! makes double-deduction a **compile error**, not a runtime check.
//!
//! # Proof structure
//!
//! 1. **Compositional** — `kani_proof()` methods generated by `#[derive(Elicit)]`
//!    verify each type in the financial type hierarchy.
//! 2. **Arithmetic invariants** — symbolic execution verifies all six outcome
//!    calculations are arithmetically correct for all valid inputs.
//! 3. **Error safety** — all invalid bet scenarios are rejected by `debit`.
//! 4. **Round-trip identities** — compose debit + settle and prove net results.
//! 5. **Token linearity** — the structural guarantee is stated as a proof
//!    comment; the compiler enforces it (use of moved value).
//!
//! # Cloud of assumptions
//!
//! - **Trust**: Rust's ownership model, u64 overflow semantics, `Established::assert()`
//! - **Verify**: Financial arithmetic, error preconditions, round-trip identities

use strictly_blackjack::{ActionError, BankrollLedger, BetDeducted, Outcome, PayoutSettled};

// ── Compositional proofs ──────────────────────────────────────────────────────

/// Verifies all financial typestate types via elicitation framework legos.
///
/// Each `kani_proof()` call is generated by `#[derive(Elicit)]` and validates
/// that the type is well-formed, all variants are reachable, and the type
/// composes correctly with its dependencies.
///
/// **Proof chain:**
/// 1. `BetDeducted` — unit proposition (one canonical value)
/// 2. `PayoutSettled` — unit proposition (one canonical value)
/// 3. `Outcome` — exhaustive enum (5 variants, each proven)
/// 4. `BankrollLedger` — composed from u64 × u64 with validated construction
/// 5. ∴ Entire financial typestate hierarchy is formally verified ∎
#[cfg(kani)]
#[kani::proof]
fn verify_bankroll_legos() {
    BetDeducted::kani_proof();
    PayoutSettled::kani_proof();
    Outcome::kani_proof();
    BankrollLedger::kani_proof();

    assert!(
        true,
        "Financial typestate legos: \
         BetDeducted × PayoutSettled × Outcome × BankrollLedger ∎"
    );
}

// ── Debit invariants ──────────────────────────────────────────────────────────

/// Verifies debit produces the correct post-bet balance.
///
/// **Property:** `∀ bankroll, bet | bet > 0 ∧ bet ≤ bankroll ⟹`
/// `debit(bankroll, bet).post_bet_balance == bankroll − bet`
#[cfg(kani)]
#[kani::proof]
fn verify_debit_arithmetic() {
    let bankroll: u64 = kani::any();
    let bet: u64 = kani::any();
    kani::assume(bet > 0);
    kani::assume(bet <= bankroll);

    let (ledger, _token) = BankrollLedger::debit(bankroll, bet).expect("valid debit");

    assert_eq!(ledger.post_bet_balance(), bankroll - bet);
    assert_eq!(ledger.bet(), bet);
}

/// Verifies zero bets are always rejected.
///
/// **Property:** `∀ bankroll, debit(bankroll, 0) == Err(InvalidBet(0))`
#[cfg(kani)]
#[kani::proof]
fn verify_debit_zero_bet_rejected() {
    let bankroll: u64 = kani::any();

    let result = BankrollLedger::debit(bankroll, 0);

    assert!(matches!(result, Err(ActionError::InvalidBet(0))));
}

/// Verifies overdraft bets are always rejected.
///
/// **Property:** `bet > bankroll ⟹ debit(bankroll, bet) == Err(InsufficientFunds(bet, bankroll))`
#[cfg(kani)]
#[kani::proof]
fn verify_debit_overdraft_rejected() {
    let bankroll: u64 = kani::any();
    let bet: u64 = kani::any();
    kani::assume(bet > bankroll);

    let result = BankrollLedger::debit(bankroll, bet);

    assert!(matches!(result, Err(ActionError::InsufficientFunds(_, _))));
}

// ── Settlement invariants ─────────────────────────────────────────────────────

/// Verifies Loss settlement: no chips returned (forfeited bet).
///
/// **Property:** `settle(Loss).final == post_bet_balance == bankroll − bet`
#[cfg(kani)]
#[kani::proof]
fn verify_settle_loss() {
    let bankroll: u64 = kani::any();
    let bet: u64 = kani::any();
    kani::assume(bet > 0);
    kani::assume(bet <= bankroll);

    let (ledger, token) = BankrollLedger::debit(bankroll, bet).expect("valid debit");
    let post_bet = ledger.post_bet_balance();
    let (final_balance, _) = ledger.settle(Outcome::Loss, token);

    assert_eq!(final_balance, post_bet);
    assert_eq!(final_balance, bankroll - bet);
}

/// Verifies Push settlement: original bet returned, net zero.
///
/// **Property:** `settle(Push).final == post_bet_balance + bet == bankroll`
#[cfg(kani)]
#[kani::proof]
fn verify_settle_push() {
    let bankroll: u64 = kani::any();
    let bet: u64 = kani::any();
    kani::assume(bet > 0);
    kani::assume(bet <= bankroll);

    let (ledger, token) = BankrollLedger::debit(bankroll, bet).expect("valid debit");
    let (final_balance, _) = ledger.settle(Outcome::Push, token);

    assert_eq!(final_balance, bankroll);
}

/// Verifies Win settlement: 2× bet returned (original + 1× profit).
///
/// **Property:** `settle(Win).final == post_bet_balance + 2*bet == bankroll + bet`
#[cfg(kani)]
#[kani::proof]
fn verify_settle_win() {
    let bankroll: u64 = kani::any();
    let bet: u64 = kani::any();
    kani::assume(bet > 0);
    kani::assume(bet <= bankroll);
    kani::assume(bet <= u64::MAX / 2);
    kani::assume(bankroll <= u64::MAX - bet);

    let (ledger, token) = BankrollLedger::debit(bankroll, bet).expect("valid debit");
    let post_bet = ledger.post_bet_balance();
    let (final_balance, _) = ledger.settle(Outcome::Win, token);

    assert_eq!(final_balance, post_bet + bet * 2);
    assert_eq!(final_balance, bankroll + bet);
}

/// Verifies Blackjack settlement: 3:2 payout (original bet + 1.5× profit).
///
/// **Property:** `settle(Blackjack).final == post_bet_balance + bet + (bet*3)/2`
///
/// Integer arithmetic: odd bets floor toward zero (house-standard).
/// E.g. bet=100 → profit=150 → gross=250; bet=101 → profit=151 → gross=252.
#[cfg(kani)]
#[kani::proof]
fn verify_settle_blackjack() {
    let bankroll: u64 = kani::any();
    let bet: u64 = kani::any();
    kani::assume(bet > 0);
    kani::assume(bet <= bankroll);
    kani::assume(bet <= u64::MAX / 3);
    kani::assume(bankroll - bet <= u64::MAX - (bet + (bet * 3) / 2));

    let (ledger, token) = BankrollLedger::debit(bankroll, bet).expect("valid debit");
    let post_bet = ledger.post_bet_balance();
    let (final_balance, _) = ledger.settle(Outcome::Blackjack, token);

    let expected_gross = bet + (bet * 3) / 2;
    assert_eq!(final_balance, post_bet + expected_gross);
}

/// Verifies Surrender settlement: half bet returned.
///
/// **Property:** `settle(Surrender).final == post_bet_balance + bet/2`
///
/// Integer arithmetic: odd bets floor toward zero (player loses the extra chip).
#[cfg(kani)]
#[kani::proof]
fn verify_settle_surrender() {
    let bankroll: u64 = kani::any();
    let bet: u64 = kani::any();
    kani::assume(bet > 0);
    kani::assume(bet <= bankroll);

    let (ledger, token) = BankrollLedger::debit(bankroll, bet).expect("valid debit");
    let post_bet = ledger.post_bet_balance();
    let (final_balance, _) = ledger.settle(Outcome::Surrender, token);

    assert_eq!(final_balance, post_bet + bet / 2);
}

// ── Structural token-linearity proof ─────────────────────────────────────────

/// Verifies the structural no-double-deduction guarantee.
///
/// **Structural guarantee (compile-time):**
/// `Established<BetDeducted>` is not `Copy`.  `settle` takes the token by
/// value (moves it).  Any attempt to call `settle` a second time with the
/// same token is a **compile error**:
///
/// ```text
/// let (ledger, token) = BankrollLedger::debit(b, x)?;
/// ledger.settle(Outcome::Win, token);       // token moved here
/// ledger.settle(Outcome::Win, token);       // ERROR: use of moved value
/// ```
///
/// **Arithmetic guarantee (Kani):**
/// The only arithmetic path from `debit` to `settle` is:
/// `final = (bankroll − bet) + gross_return(outcome, bet)`
/// — no second subtraction is possible.
#[cfg(kani)]
#[kani::proof]
fn verify_no_double_deduction() {
    let bankroll: u64 = kani::any();
    let bet: u64 = kani::any();
    kani::assume(bet > 0);
    kani::assume(bet <= bankroll);
    kani::assume(bet <= u64::MAX / 2);
    kani::assume(bankroll <= u64::MAX - bet);

    let (ledger, token) = BankrollLedger::debit(bankroll, bet).expect("valid debit");
    let post_bet = ledger.post_bet_balance();

    // Token is consumed — only one settlement is possible.
    let (final_balance, _settled) = ledger.settle(Outcome::Win, token);

    // Final balance equals (bankroll − bet) + gross_return.
    // There is no code path that subtracts `bet` a second time.
    assert_eq!(final_balance, post_bet + bet * 2);

    // Settlement can only add to the post-bet balance — never subtract.
    assert!(final_balance >= post_bet, "settlement is always additive");
}

// ── Round-trip identities ─────────────────────────────────────────────────────

/// Verifies win round-trip: net gain equals the bet.
///
/// **Property:** `debit(b, x) |> settle(Win) == b + x`
#[cfg(kani)]
#[kani::proof]
fn verify_win_roundtrip() {
    let bankroll: u64 = kani::any();
    let bet: u64 = kani::any();
    kani::assume(bet > 0);
    kani::assume(bet <= bankroll);
    kani::assume(bankroll <= u64::MAX - bet);

    let (ledger, token) = BankrollLedger::debit(bankroll, bet).expect("valid debit");
    let (final_balance, _) = ledger.settle(Outcome::Win, token);

    assert_eq!(final_balance, bankroll + bet);
}

/// Verifies push round-trip: net effect is zero.
///
/// **Property:** `debit(b, x) |> settle(Push) == b`
#[cfg(kani)]
#[kani::proof]
fn verify_push_roundtrip() {
    let bankroll: u64 = kani::any();
    let bet: u64 = kani::any();
    kani::assume(bet > 0);
    kani::assume(bet <= bankroll);

    let (ledger, token) = BankrollLedger::debit(bankroll, bet).expect("valid debit");
    let (final_balance, _) = ledger.settle(Outcome::Push, token);

    assert_eq!(final_balance, bankroll);
}

/// Verifies loss round-trip: net loss equals the bet.
///
/// **Property:** `debit(b, x) |> settle(Loss) == b − x`
#[cfg(kani)]
#[kani::proof]
fn verify_loss_roundtrip() {
    let bankroll: u64 = kani::any();
    let bet: u64 = kani::any();
    kani::assume(bet > 0);
    kani::assume(bet <= bankroll);

    let (ledger, token) = BankrollLedger::debit(bankroll, bet).expect("valid debit");
    let (final_balance, _) = ledger.settle(Outcome::Loss, token);

    assert_eq!(final_balance, bankroll - bet);
}

/// Verifies surrender round-trip: net loss is half the bet.
///
/// **Property:** `debit(b, x) |> settle(Surrender) == b − x/2`
/// (integer: odd bets floor — player loses the extra chip)
#[cfg(kani)]
#[kani::proof]
fn verify_surrender_roundtrip() {
    let bankroll: u64 = kani::any();
    let bet: u64 = kani::any();
    kani::assume(bet > 0);
    kani::assume(bet <= bankroll);

    let (ledger, token) = BankrollLedger::debit(bankroll, bet).expect("valid debit");
    let (final_balance, _) = ledger.settle(Outcome::Surrender, token);

    // net loss = bet - bet/2 = ceil(bet/2), so final = bankroll - ceil(bet/2)
    assert_eq!(final_balance, bankroll - bet + bet / 2);
}
