//! Compositional verification for blackjack types using elicitation framework.
//!
//! This module demonstrates the "formal verification legos" pattern where types
//! snap together compositionally, with each connection formally proven safe.

#[cfg(kani)]
use elicitation::Elicitation;

use strictly_blackjack::{Card, Outcome, Rank, Suit};

/// Verifies Rank enum through elicitation's compositional verification.
///
/// The `kani_proof()` method is generated by `#[derive(Elicit)]` and proves
/// that all variants are well-formed and satisfy their contracts.
#[cfg(kani)]
#[kani::proof]
fn verify_rank_compositional() {
    Rank::kani_proof();
}

/// Verifies Suit enum through elicitation's compositional verification.
#[cfg(kani)]
#[kani::proof]
fn verify_suit_compositional() {
    Suit::kani_proof();
}

/// Verifies Card struct through elicitation's compositional verification.
///
/// **Verification by composition:**
/// - `rank`: Rank (verified enum)
/// - `suit`: Suit (verified enum)
/// - ⟹ Card is verified ∎
#[cfg(kani)]
#[kani::proof]
fn verify_card_compositional() {
    Card::kani_proof();
}

/// Verifies Outcome enum through elicitation's compositional verification.
#[cfg(kani)]
#[kani::proof]
fn verify_outcome_compositional() {
    Outcome::kani_proof();
}

/// Verifies the entire blackjack type hierarchy compositionally, with a
/// real cross-type property as the capstone.
///
/// This harness witnesses the proof chain:
/// 1. Primitives (Rank, Suit) are verified by enum exhaustiveness
/// 2. Card is verified by composition (Rank × Suit)
/// 3. Outcome is verified by enum exhaustiveness
/// 4. Capstone: any Card built from any Rank × Suit has value in 1..=11 ∎
#[cfg(kani)]
#[kani::proof]
fn verify_blackjack_legos() {
    // Layer 1: Enum types (foundational)
    Rank::kani_proof();
    Suit::kani_proof();
    Outcome::kani_proof();

    // Layer 2: Composite types (verified by composition)
    Card::kani_proof();

    // Capstone: cross-type property — any (Rank, Suit) produces a Card
    // with a valid blackjack value.  This connects the structural proofs
    // to the semantic layer rather than ending on a tautology.
    let rank: Rank = kani::any();
    let suit: Suit = kani::any();
    let card = Card::new(rank, suit);
    let v = card.value();
    assert!(v >= 1 && v <= 11, "Any Card(Rank, Suit) has value in 1..=11 ∎");
}
